site_name: BlockDecomposition documentation
repo_url: https://github.com/realopt/BlockDecomposition.jl
site_description: JuMP for block structured problems
site_author: ReAlOpt

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Home: index.md
  - Installation: Installation.md
